on: [push]
# on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.5.2
        with:
          version: 14.0
      - name: environment
        run: |
          echo "export LLVM_SYS_140_PREFIX=$LLVM_PATH" > ~/.bashrc
      - name: get_env
        run: |
          source ~/.bashrc
          echo $LLVM_SYS_140_PREFIX
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.5.2
        with:
          version: 14.0
      - run: rustup component add clippy
      - name: Set LLVM envars
        run: |
          echo "export LLVM_SYS_140_PREFIX=$LLVM_PATH" > ~/.bashrc
      - name: get_env
        run: |
          source ~/.bashrc
          echo $LLVM_SYS_140_PREFIX
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
